In [3]:
# !pip install numpy
# !pip install pandas
# !pip install tensorflow
from datetime import datetime
import json
import numpy as np
import pandas as pd
import tensorflow as tf

print(f"numpy: {np.__version__}\npandas: {pd.__version__}\ntensorflow: {tf.__version__}")

numpy: 1.22.4
pandas: 1.4.2
tensorflow: 2.9.1


In [4]:
# !pip install nltk
# !pip install sklearn
# import nltk
# nltk.download("stopwords")
from two_class_model.TwoClass import TwoClass

In [ ]:
df_emails = pd.read_csv("enron.csv")


In [6]:
ml_model = TwoClass(dataframe=df_emails, y="responsive")

In [7]:
ml_model.DeepNN_model()

Epoch 1/15


2022-06-17 19:58:53.303039: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-17 19:58:53.303181: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-17 19:58:53.303205: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-06-17 19:58:53.303225: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-06-17 19:58:53.303243: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

21/21 [==============================] - 0s 3ms/step - loss: 1.0673 - accuracy: 0.8378
Epoch 2/15
21/21 [==============================] - 0s 3ms/step - loss: 0.4258 - accuracy: 0.9470


In [ ]:
model_json = ml_model.saveDNNmodel()

In [11]:
from pathlib import Path
cur_dir = Path.cwd()
work_dir = cur_dir.parent

with open(work_dir / "model.json", "r") as fp:
    model_prev = json.load(fp)

model1 = tf.keras.models.model_from_json(model_prev)

In [10]:
model_prev = json.loads(model_prev)
type(model_json), type(model_prev)

(dict, dict)

In [13]:
x = np.random.randint(2, size=(1, 14098))

In [48]:
model1.predict(x)

array([[-0.37348866]], dtype=float32)

In [22]:
df=pd.DataFrame(columns=ml_model.cols_features)
df.loc[0,:] = 0

In [23]:
for term in test_string:
    if term in ml_model.cols_features:
        df.loc[0, term] += 1

In [26]:
df.values.shape

(1, 14098)

In [ ]:
x = np.random.randint(2, size=(1, 14098))
ml_model.model.predict(x)

In [ ]:
model1.save_weights("weightfile")

In [10]:
now = datetime.now()
now_str = now.strftime("%Y%m%d-%H-%M-%S")
ml_model.model.save(f"model-weights-{now_str}.hd5")

INFO:tensorflow:Assets written to: model-weights-20220617-19-12-17.hd5/assets


In [9]:
now = datetime.now()
now_str = now.strftime("%Y%m%d-%H-%M-%S")
ml_model.model.save(f"model-weights-{now_str}.h5")

In [41]:
with open(work_dir / "test_models" / "model.json", "r") as fp:
    local_mdl_json = json.load(fp)
local_mdl = tf.keras.models.model_from_json(json.dumps(local_mdl_json))

In [49]:
local_mdl.predict(x)

array([[0.78430796]], dtype=float32)

In [5]:
local_mdl_hd5 = tf.keras.models.load_model("model.hd5")

2022-06-17 20:09:31.276558: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-17 20:09:31.276690: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-17 20:09:31.276712: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-06-17 20:09:31.276731: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-06-17 20:09:31.276750: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [6]:
local_mdl_hd5.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1804672   
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1,812,993
Trainable params: 1,812,993
Non-trainable params: 0
_________________________________________________________________


In [8]:
local_mdl_hd5.predict(x)

1/1 [==============================] - 0s 72ms/step


array([[-2.5637417]], dtype=float32)

In [53]:
ml_model.model.predict(x)

array([[-2.6026354]], dtype=float32)

In [54]:
ml_model.model == local_mdl_hd5

False

In [12]:
with open("feature.log", "w") as fp:
    fp.write(" ".join(ml_model.cols_features))

In [22]:
tl = [1,5,74,5,11]

tl.index(111)

ValueError: 111 is not in list

In [26]:
x[0,:6], x[0,2], x[0,3], x[0,4], x[0,5], x[0,0]

(array([0, 1, 0, 0, 0, 1]), 0, 0, 0, 1, 0)